/** Owner admin interface text (Hebrew). */
export const S = {
  appTitle: 'ניהול האתר',
  brand: 'Softec Vision',
  signInTitle: 'כניסה לאזור הניהול',
  email: 'דוא"ל',
  password: 'סיסמה',
  signIn: 'כניסה',
  signingIn: 'נכנס…',
  signOut: 'יציאה',
  signedInAs: 'מחובר/ת כ-',
  errors: {
    missing: 'נא להזין דוא"ל וסיסמה.',
    invalid: 'הדוא"ל או הסיסמה שגויים.',
    'no-access': 'לחשבון זה אין הרשאת ניהול. פנו למנהל/ת האתר.',
    'admin-only': 'פעולה זו זמינה למנהל/ת בלבד.',
    notConfigured: 'אזור הניהול יופעל לאחר חיבור מסד הנתונים (Supabase).',
    saveFailed: 'השמירה נכשלה. נסו שוב.'
  },
  nav: { inquiries: 'פניות', products: 'מוצרים', site: 'לאתר' },
  inquiries: {
    title: 'פניות להצעת מחיר',
    empty: 'אין פניות להצגה.',
    date: 'תאריך',
    name: 'שם',
    company: 'חברה',
    country: 'מדינה',
    product: 'מוצר',
    status: 'סטטוס',
    open: 'פתיחה'
  },
  statuses: { all: 'הכל', new: 'חדשה', read: 'נקראה', handled: 'טופלה', archived: 'בארכיון' },
  detail: {
    back: 'חזרה לפניות',
    reference: 'מספר פנייה',
    received: 'התקבלה',
    email: 'דוא"ל',
    phone: 'טלפון',
    country: 'מדינה',
    company: 'חברה / ארגון',
    projectType: 'סוג הפרויקט',
    product: 'מוצר',
    roomDimensions: 'מידות החלל',
    requirements: 'הדרישות',
    language: 'שפת האתר',
    consent: 'הסכמה למדיניות הפרטיות',
    attachments: 'קבצים מצורפים',
    noAttachments: 'אין קבצים מצורפים.',
    fileLinkNote: 'הקישורים תקפים ל-5 דקות.',
    reply: 'מענה',
    replyEmail: 'השב בדוא"ל',
    replyPhone: 'התקשר',
    replyWhatsapp: 'WhatsApp',
    setStatus: 'סטטוס הפנייה',
    erase: 'מחיקה לצמיתות',
    eraseHelp: 'לבקשת מחיקת מידע אישי. מוחק את הפנייה ואת הקבצים המצורפים — לא ניתן לשחזר.',
    eraseConfirm: 'אני מאשר/ת מחיקה לצמיתות',
    eraseButton: 'מחיקת הפנייה',
    erased: 'הפנייה והקבצים המצורפים נמחקו.',
    policyVersion: 'גרסת המדיניות',
    notFound: 'הפנייה לא נמצאה.'
  },
  products: {
    title: 'מוצרים',
    empty: 'אין מוצרים להצגה.',
    code: 'קוד',
    name: 'שם',
    category: 'קטגוריה',
    status: 'סטטוס',
    missing: 'מפרט חסר',
    missingCount: (n: number) => `${n} שדות חסרים`,
    complete: 'מלא',
    edit: 'עריכה',
    back: 'חזרה למוצרים',
    save: 'שמירה',
    saving: 'שומר…',
    saved: 'המוצר נשמר.',
    notFound: 'המוצר לא נמצא.',
    nameSection: 'שם ותיאור',
    specsSection: 'מפרט טכני',
    specsHelp: 'שדה ריק לא יוצג באתר. יש למלא שתי השפות יחד, או להשאיר ריק.',
    alt: 'טקסט חלופי לתמונה',
    altHelp: 'לתיאור התמונה למי שמשתמש בקורא מסך. השאירו ריק להשתמש בברירת המחדל.',
    hebrew: 'עברית',
    english: 'אנגלית',
    statuses: { draft: 'טיוטה', published: 'פורסם', archived: 'בארכיון' },
    statusHelp: 'רק מוצרים "פורסם" מוצגים באתר.',
    import: {
      title: 'ייבוא קטלוג התחלתי',
      help: 'הקטלוג עדיין לא יובא למסד הנתונים — האתר מציג את הנתונים המובנים. הייבוא חד-פעמי: הוא מוסיף כל מוצר שאינו קיים כבר, ולא דורס עריכות קודמות אם ירוץ שוב.',
      button: 'ייבוא הקטלוג',
      done: (n: number) => `הקטלוג יובא: ${n} מוצרים נוספו.`
    },
    fieldErrors: {
      required: 'שדה חובה.',
      tooLong: 'הטקסט ארוך מדי.',
      placeholder: 'יש להזין ערך אמיתי — לא ניתן לפרסם טקסט ממתין למילוי.',
      bothLanguages: 'יש למלא את השדה בשתי השפות, או להשאיר את שתיהן ריקות.',
      invalid: 'ערך לא תקין.'
    }
  }
} as const;
